# This is a basic workflow to help you get started with Actions

name: CI + CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: NPM Install  
        run: npm install
      - name: NPM Build  
        run: npm run build
        env:
         CI: true
      # Runs a single command using the runners shell
      - name: AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
                 
          
      - name: AWS S3 Sync     
        run: aws s3 sync ./dist/my-app s3://angularappp
      # Runs a set of commands using the runners shell
  DeployDev: 
    name: Deploy To Development
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: development
      url: 'http://dev.site'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: NPM Install  
        run: npm install
      - name: NPM Build  
        run: npm run build
        env:
         CI: true
      # Runs a single command using the runners shell
      - name: AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
                 
          
      - name: AWS S3 Sync     
        run: aws s3 sync ./dist/my-app s3://angularappp
  DeployProd:
    name: Deploy To Production
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'http://prod.site'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: NPM Install  
        run: npm install
      - name: NPM Build  
        run: npm run build
        env:
         CI: true
      # Runs a single command using the runners shell
      - name: AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
                 
          
      - name: AWS S3 Sync     
        run: aws s3 sync ./dist/my-app s3://angularappp
